# Generated by Django 5.1.1 on 2024-10-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='stripe_payment_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_status',
        ),
    ]
