# Generated by Django 5.1.2 on 2024-10-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_stripe_payment_intent_id_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Sample', max_length=255),
        ),
    ]
