# Generated by Django 5.1.2 on 2024-10-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
